SET FOREIGN_KEY_CHECKS=0;

LOAD DATA LOCAL INFILE 'C:\\CIS_PRO_FILES\\MERGE_CIS\\indv\\visit.csv' 
INTO TABLE apindb.visit
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(visittype, visitdate, pepid);

SET FOREIGN_KEY_CHECKS=1;